import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import '@testing-library/jest-dom';
import { ConnectGitHub, DisconnectGitHub } from '../components/ConnectGitHub';
import { auth } from '../firebase-config';

// Create mock for firebase auth
jest.mock('../../src/firebase-config', () => ({
  auth: {
    currentUser: null,
  },
}));

// Create a mock window.location.href
delete (window as any).location;
(window as any).location = { href: '' };
global.fetch = jest.fn();
(window as any).open = jest.fn();

describe('ConnectGitHub Component', () => {
  beforeEach(() => {
    window.alert = jest.fn();
    window.location.href = '';
  });

  test('has a connect button', () => {
    render(<ConnectGitHub />);
    const button = screen.getByText('Connect GitHub');
    expect(button).toBeInTheDocument();
  });

  test('has redirect logic', () => {
    // Mock authenticated user for this test
    (auth as any).currentUser = { uid: 'test-user-123' };
    
    render(<ConnectGitHub />);
    const button = screen.getByText('Connect GitHub');
    fireEvent.click(button);
    
    expect(window.location.href).toContain('githubInstall');
  });

  test('has authentication check logic', () => {
    // Set user to null for this test
    (auth as any).currentUser = null;
    
    render(<ConnectGitHub />);
    const button = screen.getByText('Connect GitHub');
    fireEvent.click(button);
    
    expect(window.alert).toHaveBeenCalled();
  });
});

describe('DisconnectGitHub Component', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    window.alert = jest.fn();
    (window as any).open = jest.fn();
    console.error = jest.fn();
    console.warn = jest.fn();
  });

  test('has a disconnect button', () => {
    render(<DisconnectGitHub />);
    const button = screen.getByText('Disconnect GitHub');
    expect(button).toBeInTheDocument();
  });

  test('has authentication check logic', () => {
    (auth as any).currentUser = null;

    render(<DisconnectGitHub />);
    const button = screen.getByText('Disconnect GitHub');
    fireEvent.click(button);

    expect(window.alert).toHaveBeenCalled();
  });
  /* Generated by Claude Code from this point and down to get 100% coverage */
  test('disconnects successfully with redirect URL', async () => {
    // Mock authenticated user
    (auth as any).currentUser = { uid: 'test-user-123' };

    // Mock successful response with redirectUrl
    (global.fetch as jest.Mock).mockResolvedValue({
      json: async () => ({
        success: true,
        redirectUrl: 'https://github.com/apps/test-app/installations/123'
      })
    });

    render(<DisconnectGitHub />);
    const button = screen.getByText('Disconnect GitHub');
    fireEvent.click(button);

    await waitFor(() => {
      expect(window.alert).toHaveBeenCalledWith('GitHub disconnected successfully');
    });
    expect(window.open).toHaveBeenCalledWith('https://github.com/apps/test-app/installations/123', '_blank');
  });

  test('disconnects successfully without redirect URL', async () => {
    // Mock authenticated user
    (auth as any).currentUser = { uid: 'test-user-123' };

    // Mock successful response without redirectUrl
    (global.fetch as jest.Mock).mockResolvedValue({
      json: async () => ({ success: true })
    });

    render(<DisconnectGitHub />);
    const button = screen.getByText('Disconnect GitHub');
    fireEvent.click(button);

    await waitFor(() => {
      expect(window.alert).toHaveBeenCalledWith('GitHub disconnected successfully');
    });
    expect(window.open).not.toHaveBeenCalled();
  });

  test('shows error when server returns failure', async () => {
    // Mock authenticated user
    (auth as any).currentUser = { uid: 'test-user-123' };

    // Mock server failure response
    (global.fetch as jest.Mock).mockResolvedValue({
      json: async () => ({ success: false })
    });

    render(<DisconnectGitHub />);
    const button = screen.getByText('Disconnect GitHub');
    fireEvent.click(button);

    await waitFor(() => {
      expect(window.alert).toHaveBeenCalledWith('Failed to disconnect GitHub.');
    });
    expect(window.open).not.toHaveBeenCalled();
  });

  test('handles network errors gracefully', async () => {
    // Mock authenticated user
    (auth as any).currentUser = { uid: 'test-user-123' };

    // Mock network error
    const networkError = new Error('Network error');
    (global.fetch as jest.Mock).mockRejectedValue(networkError);

    render(<DisconnectGitHub />);
    const button = screen.getByText('Disconnect GitHub');
    fireEvent.click(button);

    await waitFor(() => {
      expect(console.error).toHaveBeenCalledWith('Error disconnecting:', networkError);
    });
    expect(window.alert).toHaveBeenCalledWith('Failed to disconnect GitHub');
  });

  test('verifies fetch called with correct parameters', async () => {
    // Mock authenticated user
    (auth as any).currentUser = { uid: 'test-user-123' };

    (global.fetch as jest.Mock).mockResolvedValue({
      json: async () => ({ success: true })
    });

    render(<DisconnectGitHub />);
    const button = screen.getByText('Disconnect GitHub');
    fireEvent.click(button);

    await waitFor(() => {
      expect(global.fetch).toHaveBeenCalledWith(
        expect.stringContaining('disconnectGitHub'),
        expect.objectContaining({
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ userId: 'test-user-123' })
        })
      );
    });
  });
});