import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import '@testing-library/jest-dom';
import { ConnectGitHub, DisconnectGitHub } from '../components/ConnectGitHub';

// Simple mock - just mock the module
jest.mock('../firebase-config', () => ({
  auth: {
    currentUser: null,
  },
}));

<<<<<<< HEAD
// Create a mock window.location.href
delete (window as any).location;
(window as any).location = { href: '' };
global.fetch = jest.fn();
(window as any).open = jest.fn();

=======
>>>>>>> 67a3b911440c531159c00cce442c34aba124b373
describe('ConnectGitHub Component', () => {
  beforeEach(() => {
    window.alert = jest.fn();
    // Simple location mock
    delete (window as any).location;
    (window as any).location = { href: '' };
  });

  test('renders connect button', () => {
    render(<ConnectGitHub />);
    expect(screen.getByText('Connect GitHub')).toBeInTheDocument();
  });

  test('shows alert when not authenticated', () => {
    render(<ConnectGitHub />);
    fireEvent.click(screen.getByText('Connect GitHub'));
    expect(window.alert).toHaveBeenCalledWith('Please log in first');
  });
});

describe('DisconnectGitHub Component', () => {
  beforeEach(() => {
    window.alert = jest.fn();
<<<<<<< HEAD
    (window as any).open = jest.fn();
    console.error = jest.fn();
    console.warn = jest.fn();
=======
    global.fetch = jest.fn();
>>>>>>> 67a3b911440c531159c00cce442c34aba124b373
  });

  test('renders disconnect button', () => {
    render(<DisconnectGitHub />);
    expect(screen.getByText('Disconnect GitHub')).toBeInTheDocument();
  });

<<<<<<< HEAD
  test('has authentication check logic', () => {
    (auth as any).currentUser = null;

    render(<DisconnectGitHub />);
    const button = screen.getByText('Disconnect GitHub');
    fireEvent.click(button);

    expect(window.alert).toHaveBeenCalled();
  });
  /* Generated by Claude Code from this point and down to get 100% coverage */
  test('disconnects successfully with redirect URL', async () => {
    // Mock authenticated user
    (auth as any).currentUser = { uid: 'test-user-123' };

    // Mock successful response with redirectUrl
    (global.fetch as jest.Mock).mockResolvedValue({
      json: async () => ({
        success: true,
        redirectUrl: 'https://github.com/apps/test-app/installations/123'
      })
    });

    render(<DisconnectGitHub />);
    const button = screen.getByText('Disconnect GitHub');
    fireEvent.click(button);

    await waitFor(() => {
      expect(window.alert).toHaveBeenCalledWith('GitHub disconnected successfully');
    });
    expect(window.open).toHaveBeenCalledWith('https://github.com/apps/test-app/installations/123', '_blank');
  });

  test('disconnects successfully without redirect URL', async () => {
    // Mock authenticated user
    (auth as any).currentUser = { uid: 'test-user-123' };

    // Mock successful response without redirectUrl
    (global.fetch as jest.Mock).mockResolvedValue({
      json: async () => ({ success: true })
    });

    render(<DisconnectGitHub />);
    const button = screen.getByText('Disconnect GitHub');
    fireEvent.click(button);

    await waitFor(() => {
      expect(window.alert).toHaveBeenCalledWith('GitHub disconnected successfully');
    });
    expect(window.open).not.toHaveBeenCalled();
  });

  test('shows error when server returns failure', async () => {
    // Mock authenticated user
    (auth as any).currentUser = { uid: 'test-user-123' };

    // Mock server failure response
    (global.fetch as jest.Mock).mockResolvedValue({
      json: async () => ({ success: false })
    });

    render(<DisconnectGitHub />);
    const button = screen.getByText('Disconnect GitHub');
    fireEvent.click(button);

    await waitFor(() => {
      expect(window.alert).toHaveBeenCalledWith('Failed to disconnect GitHub.');
    });
    expect(window.open).not.toHaveBeenCalled();
  });

  test('handles network errors gracefully', async () => {
    // Mock authenticated user
    (auth as any).currentUser = { uid: 'test-user-123' };

    // Mock network error
    const networkError = new Error('Network error');
    (global.fetch as jest.Mock).mockRejectedValue(networkError);

    render(<DisconnectGitHub />);
    const button = screen.getByText('Disconnect GitHub');
    fireEvent.click(button);

    await waitFor(() => {
      expect(console.error).toHaveBeenCalledWith('Error disconnecting:', networkError);
    });
    expect(window.alert).toHaveBeenCalledWith('Failed to disconnect GitHub');
  });

  test('verifies fetch called with correct parameters', async () => {
    // Mock authenticated user
    (auth as any).currentUser = { uid: 'test-user-123' };

    (global.fetch as jest.Mock).mockResolvedValue({
      json: async () => ({ success: true })
    });

    render(<DisconnectGitHub />);
    const button = screen.getByText('Disconnect GitHub');
    fireEvent.click(button);

    await waitFor(() => {
      expect(global.fetch).toHaveBeenCalledWith(
        expect.stringContaining('disconnectGitHub'),
        expect.objectContaining({
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ userId: 'test-user-123' })
        })
      );
    });
  });
});
=======
  test('shows alert when not authenticated', () => {
    render(<DisconnectGitHub />);
    fireEvent.click(screen.getByText('Disconnect GitHub'));
    expect(window.alert).toHaveBeenCalledWith('Please log in first');
  });
});
>>>>>>> 67a3b911440c531159c00cce442c34aba124b373
